let pf2eConf = {};

pf2eConf.actorSizes = {
  grg: "Gargantuan",
  huge: "Huge",
  lg: "Large",
  med: "Medium",
  sm: "Small",
  tiny: "Tiny",
};

pf2eConf.alignment = {
  CE: "Chaotic Evil",
  CG: "Chaotic Good",
  CN: "Chaotic Neutral",
  LE: "Lawful Evil",
  LG: "Lawful Good",
  LN: "Lawful Neutral",
  N: "Neutral",
  NE: "Neutral Evil",
  NG: "Neutral Good",
};

pf2eConf.abilities = {
  cha: "Charisma",
  con: "Constitution",
  dex: "Dexterity",
  int: "Intelligence",
  str: "Strength",
  wis: "Wisdom",
};

pf2eConf.languages = {
  abyssal: "Abyssal",
  aklo: "Aklo",
  algollthu: "Algollthu",
  amurrun: "Amurrun",
  anadi: "Anadi",
  aquan: "Aquan",
  arboreal: "Arboreal",
  auran: "Auran",
  azlanti: "Azlanti",
  boggard: "Boggard",
  caligni: "Caligni",
  celestial: "Celestial",
  common: "Common",
  cyclops: "Cyclops",
  daemonic: "Daemonic",
  destrachan: "Destrachan",
  draconic: "Draconic",
  druidic: "Druidic",
  dwarven: "Dwarven",
  dziriak: "D'ziriak",
  elven: "Elven",
  erutaki: "Erutaki",
  garundi: "Garundi",
  gnoll: "Gnoll",
  gnomish: "Gnomish",
  goblin: "Goblin",
  grippli: "Grippli",
  halfling: "Halfling",
  hallit: "Hallit",
  ignan: "Ignan",
  infernal: "Infernal",
  iruxi: "Iruxi",
  jistkan: "Jistkan",
  jotun: "Jotun",
  jyoti: "Jyoti",
  kelish: "Kelish",
  mwangi: "Mwangi",
  necril: "Necril",
  orcish: "Orcish",
  osiriani: "Osiriani",
  protean: "Protean",
  requian: "Requian",
  shadowtongue: "Shadowtongue",
  shoanti: "Shoanti",
  shoony: "Shoony",
  skald: "Skald",
  sphinx: "Sphinx",
  strix: "Strix",
  sylvan: "Sylvan",
  tengu: "Tengu",
  terran: "Terran",
  thassilonian: "Thassilonian",
  tien: "Tien",
  undercommon: "Undercommon",
  utopian: "Utopian",
  varisian: "Varisian",
  varki: "Varki",
  vudrani: "Vudrani",
  ysoki: "Ysoki",
};

pf2eConf.resistanceTypes = {
  acid: "Acid",
  all: "All",
  bleed: "Bleed",
  bludgeoning: "Bludgeoning",
  chaotic: "Chaotic",
  cold: "Cold",
  "critical-hits": "Critical Hits",
  "draconic resistance": "Dragon Resistance",
  electricity: "Electricity",
  evil: "Evil",
  fire: "Fire",
  force: "Force",
  good: "Good",
  lawful: "Lawful",
  mental: "Mental",
  negative: "Negative",
  physical: "Physical",
  piercing: "Piercing",
  poison: "Poison",
  positive: "Positive",
  precision: "Precision",
  "protean anatomy": "Protean Anatomy",
  slashing: "Slashing",
  sonic: "Sonic",
  weapon: "Weapons",
};

pf2eConf.immunityTypes = {
  acid: "Acid",
  bleed: "Bleed",
  blinded: "Blinded",
  bludgeoning: "Bludgeoning",
  broken: "Broken",
  chaotic: "Chaotic",
  clumsy: "Clumsy",
  cold: "Cold",
  concealed: "Concealed",
  confused: "Confused",
  confusion: "Confusion",
  controlled: "Controlled",
  "critical-hits": "Critical Hits",
  curse: "Curse",
  dazzled: "Dazzled",
  deafened: "Deafened",
  "death effects": "Death Effects",
  disease: "Disease",
  doomed: "Doomed",
  drained: "Drained",
  dying: "Dying",
  electricity: "Electricity",
  emotion: "Emotion",
  encumbered: "Encumbered",
  enfeebled: "Enfeebled",
  evil: "Evil",
  fascinated: "Fascinated",
  fatigued: "Fatigued",
  "fear effects": "Fear",
  fire: "Fire",
  "flat-footed": "Flat-Footed",
  fleeing: "Fleeing",
  force: "Force",
  friendly: "Friendly",
  frightened: "Frightened",
  good: "Good",
  grabbed: "Grabbed",
  healing: "Healing",
  helpful: "Helpful",
  hidden: "Hidden",
  hostile: "Hostile",
  immobilized: "Immobilized",
  indifferent: "Indifferent",
  invisible: "Invisible",
  lawful: "Lawful",
  light: "Light",
  magic: "Magic",
  mental: "Mental",
  necromancy: "Necromancy",
  negative: "Negative",
  "nonlethal attacks": "Nonlethal Attacks",
  "object-immunities": "Object Immunities",
  observed: "Observed",
  olfactory: "Olfactory",
  paralyzed: "Paralyzed",
  persistent: "Persistent Damage",
  petrified: "Petrified",
  piercing: "Piercing",
  poison: "Poison",
  positive: "Positive",
  possession: "Posession",
  precision: "Precision",
  "precision-damage": "Precision Damage",
  prone: "Prone",
  quickened: "Quickened",
  restrained: "Restrained",
  sickened: "Sickened",
  slashing: "Slashing",
  sleep: "Sleep",
  slowed: "Slowed",
  sonic: "Sonic",
  spellDeflection: "Spell Deflection",
  stunned: "Stunned",
  stupefied: "Stupefied",
  "swarm attacks": "Swarm Attacks",
  "swarm-mind": "Swarm Mind",
  unconscious: "Unconscious",
  undetected: "Undetected",
  unfriendly: "Unfriendly",
  unnoticed: "Unnoticed",
  visual: "Visual",
  wounded: "Wounded",
};

pf2eConf.weaknessTypes = {
  acid: "Acid",
  adamantine: "Adamantine",
  "area-damage": "Area Damage",
  bleed: "Bleed",
  bludgeoning: "Bludgeoning",
  chaotic: "Chaotic",
  cold: "Cold",
  coldiron: "Cold Iron",
  darkwood: "Darkwood",
  electricity: "Electricity",
  evil: "Evil",
  fire: "Fire",
  force: "Force",
  good: "Good",
  lawful: "Lawful",
  light: "Light",
  mental: "Mental",
  mithral: "Mithral",
  negative: "Negative",
  orichalcum: "Orichalcum",
  piercing: "Piercing",
  poison: "Poison",
  positive: "Positive",
  precision: "Precision",
  salt: "PF2E.WeaknessTypeSalt",
  "salt water": "Salt Water",
  silver: "Silver",
  slashing: "Slashing",
  sonic: "Sonic",
  "splash-damage": "Splash Damage",
  "vampire weaknesses": "Vampire Weaknesses",
  "vorpal fear": "Vorpal Fear",
  "vorpal weapons": "Vorpal Weapons",
};

pf2eConf.monsterTraits = {
  aasimar: "Aasimar",
  aberration: "aberration",
  acid: "Acid",
  aeon: "aeon",
  air: "Air",
  alchemical: "Alchemical",
  amphibious: "amphibious",
  anadi: "anadi",
  angel: "angel",
  animal: "animal",
  aquatic: "aquatic",
  archon: "archon",
  astral: "astral",
  azata: "azata",
  beast: "beast",
  bleed: "Bleed",
  bludgeoning: "Bludgeoning",
  boggard: "boggard",
  caligni: "caligni",
  catfolk: "Catfolk",
  celestial: "celestial",
  changeling: "Changeling",
  chaotic: "Chaotic",
  "charau-ka": "charau-ka",
  cold: "Cold",
  construct: "construct",
  couatl: "Couatl",
  daemon: "daemon",
  demon: "demon",
  dero: "dero",
  devil: "devil",
  dhampir: "Dhampir",
  dinosaur: "dinosaur",
  dragon: "dragon",
  dream: "Dream",
  drow: "drow",
  duergar: "duergar",
  duskwalker: "Duskwalker",
  dwarf: "Dwarf",
  earth: "Earth",
  electricity: "Electricity",
  elemental: "elemental",
  elf: "Elf",
  ethereal: "ethereal",
  evil: "Evil",
  fetchling: "Fetchling",
  fey: "fey",
  fiend: "fiend",
  fire: "Fire",
  force: "Force",
  fungus: "Fungus",
  genie: "genie",
  geniekin: "Geniekin",
  ghost: "ghost",
  ghoul: "ghoul",
  giant: "giant",
  gnoll: "gnoll",
  gnome: "Gnome",
  goblin: "Goblin",
  golem: "golem",
  good: "Good",
  gremlin: "gremlin",
  grippli: "grippli",
  hag: "hag",
  "half-elf": "Half-Elf",
  "half-orc": "Half-Orc",
  halfling: "Halfling",
  hobgoblin: "Hobgoblin",
  human: "Human",
  humanoid: "humanoid",
  ifrit: "Ifrit",
  incorporeal: "incorporeal",
  inevitable: "inevitable",
  kobold: "Kobold",
  lawful: "Lawful",
  leshy: "Leshy",
  lizardfolk: "Lizardfolk",
  mental: "Mental",
  merfolk: "merfolk",
  mindless: "mindless",
  minion: "Minion",
  monitor: "monitor",
  mummy: "mummy",
  mutant: "mutant",
  negative: "Negative",
  nymph: "nymph",
  oni: "Oni",
  ooze: "ooze",
  orc: "Orc",
  oread: "Oread",
  petitioner: "Petitioner",
  piercing: "Piercing",
  plant: "Plant",
  poison: "Poison",
  positive: "Positive",
  precision: "Precision",
  protean: "protean",
  psychopomp: "psychopomp",
  qlippoth: "Qlippoth",
  rakshasa: "rakshasa",
  ratfolk: "Ratfolk",
  "sea devil": "sea devil",
  serpentfolk: "Serpentfolk",
  shadow: "Shadow",
  shoony: "Shoony",
  skeleton: "skeleton",
  skulk: "Skulk",
  slashing: "Slashing",
  sonic: "Sonic",
  soulbound: "soulbound",
  spirit: "spirit",
  spriggan: "Spriggan",
  sprite: "sprite",
  suli: "Suli",
  swarm: "swarm",
  sylph: "Sylph",
  tane: "Tane",
  tengu: "Tengu",
  tiefling: "Tiefling",
  time: "Time",
  troll: "troll",
  undead: "undead",
  undine: "Undine",
  urdefhan: "Urdefhan",
  vampire: "vampire",
  velstrac: "velstrac",
  water: "Water",
  werecreature: "werecreature",
  wight: "wight",
  wraith: "wraith",
  xulgath: "xulgath",
  zombie: "zombie",
};

pf2eConf.saves = {
  fortitude: "Fortitude",
  reflex: "Reflex",
  will: "Will",
};

pf2eConf.proficiencyLevels = {
  0: "Untrained",
  1: "Trained",
  2: "Expert",
  3: "Master",
  4: "Legendary",
};

pf2eConf.heroPointLevels = {
  0: "Zero Hero Points",
  1: "One Hero Point",
  2: "Two Hero Points",
  3: "Three Hero Points",
};

pf2eConf.martialSkills = {
  advanced: "Advanced Weapons",
  heavy: "Heavy Armor",
  light: "Light Armor",
  martial: "Martial Weapons",
  medium: "Medium Armor",
  simple: "Simple Weapons",
  unarmed: "Unarmed",
  unarmored: "Unarmored",
};

pf2eConf.skills = {
  acr: "Acrobatics",
  arc: "Arcana",
  ath: "Athletics",
  cra: "Crafting",
  dec: "Deception",
  dip: "Diplomacy",
  itm: "Intimidation",
  med: "Medicine",
  nat: "Nature",
  occ: "Occultism",
  prf: "Performance",
  rel: "Religion",
  soc: "Society",
  ste: "Stealth",
  sur: "Survival",
  thi: "Thievery",
};

pf2eConf.currencies = {
  cp: "Copper",
  gp: "Gold",
  pp: "Platinum",
  sp: "Silver",
};

pf2eConf.spellLevels = {
  0: "Cantrip",
  1: "1st Level",
  2: "2nd Level",
  3: "3rd Level",
  4: "4th Level",
  5: "5th Level",
  6: "6th Level",
  7: "7th Level",
  8: "8th Level",
  9: "9th Level",
  10: "10th Level",
};

pf2eConf.areaSizes = {
  5: "5 Foot",
  10: "10 Foot",
  15: "15 Foot",
  20: "20 Foot",
  30: "30 Foot",
  40: "40 Foot",
  50: "50 Foot",
  60: "60 Foot",
  120: "120 Foot",
};

pf2eConf.areaTypes = {
  burst: "Burst",
  cone: "Cone",
  emanation: "Emanation",
  line: "Line",
};

pf2eConf.magicTraditions = {
  arcane: "Arcane",
  divine: "Divine",
  focus: "Focus",
  occult: "Occult",
  primal: "Primal",
  ritual: "Ritual",
  scroll: "Scroll",
  wand: "Wand",
};

pf2eConf.preparationType = {
  innate: "Innate",
  prepared: "Prepared",
  spontaneous: "Spontaneous",
};

pf2eConf.spellSchools = {
  abj: "Abjuration",
  con: "Conjuration",
  div: "Divination",
  enc: "Enchantment",
  evo: "Evocation",
  ill: "Illusion",
  nec: "Necromancy",
  trs: "Transmutation",
};

export default pf2eConf;
